# Generated by Django 2.1.2 on 2018-11-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superdealzapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='error',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='precio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='supermercado',
            options={'managed': False},
        ),
    ]
