# Generated by Django 2.1.2 on 2018-11-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superdealzapp', '0002_auto_20181102_2145'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='error',
            table='error',
        ),
        migrations.AlterModelTable(
            name='precio',
            table='precio',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='supermercado',
            table='supermercado',
        ),
    ]
